apiVersion: apps/v1
kind: Deployment
metadata:
  name: hub-management-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hub-management-service
  template:
    metadata:
      labels:
        app: hub-management-service
    spec:
      containers:
        - name: hub-management-service
          image: ayoubajdour/hub-management-service:latest
          ports:
            - containerPort: 8083
          env:
            - name: MONGO_URI
              value: mongodb://mongodb:27017/hub_management_db
          command: [ "sh", "-c", "sleep 10 && npm start" ]
          livenessProbe:
            httpGet:
              path: /health
              port: 8083
            initialDelaySeconds: 10
            periodSeconds: 30
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health
              port: 8083
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 3

---
apiVersion: v1
kind: Service
metadata:
  name: hub-management-service
spec:
  selector:
    app: hub-management-service
  ports:
    - protocol: TCP
      port: 8083
      targetPort: 8083
  type: LoadBalancer
