apiVersion: batch/v1
kind: Job
metadata:
  name: kong-migrations
spec:
  template:
    spec:
      containers:
      - name: kong-migrations
        image: kong:3.5
        command: [ "/bin/sh", "-c", "kong migrations bootstrap" ]
        env:
          - name: KONG_DATABASE
            value: "postgres"
          - name: KONG_PG_HOST
            value: "kong-database"
          - name: KONG_PG_USER
            value: "kong"
          - name: KONG_PG_PASSWORD
            value: "kong"
          - name: KONG_PG_DATABASE
            value: "kong"
      restartPolicy: OnFailure