apiVersion: v1
kind: Service
metadata:
  name: kong-gateway
spec:
  selector:
    app: kong-gateway
  ports:
    - name: proxy
      port: 8000
      targetPort: 8000
    - name: proxy-ssl
      port: 8443
      targetPort: 8443
    - name: admin-api
      port: 8001
      targetPort: 8001
    - name: kong-manager  # Added Kong Manager port
      port: 8002
      targetPort: 8002
  type: LoadBalancer